# Generated by Django 4.2.22 on 2025-07-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_add_initial_permissions'),
    ]

    operations = [
    ]
