# Generated by Django 4.2.22 on 2025-07-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),  # Changed from '0002_initial_roles_and_permissions'
    ]

    operations = [
    ]
