# Generated by Django 4.2.22 on 2025-07-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_add_initial_roles'),
        ('roles', '0003_auto_20250709_1731'),
    ]

    operations = [
    ]
