"""
Django settings for tupian project.

Generated by 'django-admin startproject' using Django 4.2.22.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-snwt^bitrh3=$-xi9@o(azyfu=b+h5q=l861c6zuyd71-7r9u4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # 添加CORS应用
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'files',
    'categories',
    'roles',
    'permissions',
    # 'rest_framework_simplejwt.token_blacklist',  # 注释或删除此行
]

# 修正为大写的AUTH_USER_MODEL
AUTH_USER_MODEL = 'users.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 添加CORS中间件
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tupian.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tupian.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'tupian',  # 你的 MySQL 数据库名（需提前在 MySQL 中创建）
        'USER': 'root',       # MySQL 用户名
        'PASSWORD': '123456789', # MySQL 密码
        'HOST': '127.0.0.1',  # 数据库地址
        'PORT': '3306',       # 端口
        'OPTIONS': {
            'charset': 'utf8mb4',  # 支持 emoji 字符
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

# 添加JWT配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # 访问令牌有效期1小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 刷新令牌有效期7天
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,  # 禁用黑名单功能，因为已移除token_blacklist应用
    'AUTH_HEADER_TYPES': ('Bearer',),  # 添加认证头类型设置
}


# 七牛云配置
QINIU_ACCESS_KEY = 'sn-Z6WhfwMvTDLDEcoZlNCAe2fsIRnkJ4O25CeNi'
QINIU_SECRET_KEY = 'URGrex3ddiDAfeXSD2r8okGChmDK1zlwLH_9gyB6'
QINIU_BUCKET_NAME = 'zhhibo'
QINIU_DOMAIN = 'szzh7g7ua.hn-bkt.clouddn.com'  # 你的七牛云域名
QINIU_UPLOAD_URL = 'https://upload-z2.qiniup.com'  # 上传地址


# 添加CORS配置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",  # Vue开发服务器地址
    "http://127.0.0.1:8080",
]

# 开发环境可临时允许所有源（生产环境不推荐）
# CORS_ALLOW_ALL_ORIGINS = True

# 允许前端携带cookie（如果需要）
# CORS_ALLOW_CREDENTIALS = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # 更新允许的主机